// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/notification/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// TelegramService is an autogenerated mock type for the TelegramService type
type TelegramService struct {
	mock.Mock
}

type TelegramService_Expecter struct {
	mock *mock.Mock
}

func (_m *TelegramService) EXPECT() *TelegramService_Expecter {
	return &TelegramService_Expecter{mock: &_m.Mock}
}

// SendOrderAssembledNotification provides a mock function with given fields: ctx, shipAssembledEvent
func (_m *TelegramService) SendOrderAssembledNotification(ctx context.Context, shipAssembledEvent model.ShipAssembledEvent) error {
	ret := _m.Called(ctx, shipAssembledEvent)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderAssembledNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = rf(ctx, shipAssembledEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendOrderAssembledNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderAssembledNotification'
type TelegramService_SendOrderAssembledNotification_Call struct {
	*mock.Call
}

// SendOrderAssembledNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - shipAssembledEvent model.ShipAssembledEvent
func (_e *TelegramService_Expecter) SendOrderAssembledNotification(ctx interface{}, shipAssembledEvent interface{}) *TelegramService_SendOrderAssembledNotification_Call {
	return &TelegramService_SendOrderAssembledNotification_Call{Call: _e.mock.On("SendOrderAssembledNotification", ctx, shipAssembledEvent)}
}

func (_c *TelegramService_SendOrderAssembledNotification_Call) Run(run func(ctx context.Context, shipAssembledEvent model.ShipAssembledEvent)) *TelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledEvent))
	})
	return _c
}

func (_c *TelegramService_SendOrderAssembledNotification_Call) Return(_a0 error) *TelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendOrderAssembledNotification_Call) RunAndReturn(run func(context.Context, model.ShipAssembledEvent) error) *TelegramService_SendOrderAssembledNotification_Call {
	_c.Call.Return(run)
	return _c
}

// SendOrderPaidNotification provides a mock function with given fields: ctx, orderPaidEvent
func (_m *TelegramService) SendOrderPaidNotification(ctx context.Context, orderPaidEvent model.OrderPaidEvent) error {
	ret := _m.Called(ctx, orderPaidEvent)

	if len(ret) == 0 {
		panic("no return value specified for SendOrderPaidNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = rf(ctx, orderPaidEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TelegramService_SendOrderPaidNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOrderPaidNotification'
type TelegramService_SendOrderPaidNotification_Call struct {
	*mock.Call
}

// SendOrderPaidNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - orderPaidEvent model.OrderPaidEvent
func (_e *TelegramService_Expecter) SendOrderPaidNotification(ctx interface{}, orderPaidEvent interface{}) *TelegramService_SendOrderPaidNotification_Call {
	return &TelegramService_SendOrderPaidNotification_Call{Call: _e.mock.On("SendOrderPaidNotification", ctx, orderPaidEvent)}
}

func (_c *TelegramService_SendOrderPaidNotification_Call) Run(run func(ctx context.Context, orderPaidEvent model.OrderPaidEvent)) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidEvent))
	})
	return _c
}

func (_c *TelegramService_SendOrderPaidNotification_Call) Return(_a0 error) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TelegramService_SendOrderPaidNotification_Call) RunAndReturn(run func(context.Context, model.OrderPaidEvent) error) *TelegramService_SendOrderPaidNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewTelegramService creates a new instance of TelegramService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramService {
	mock := &TelegramService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
