with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/nkolesnikov999/micro2-OK/inventory/internal/service:
    config:
      include-regex: ".*Service"

  github.com/nkolesnikov999/micro2-OK/inventory/internal/repository:
    config:
        include-regex: ".*Repository"

  github.com/nkolesnikov999/micro2-OK/inventory/internal/config:
    config:
      include-regex: ".*Config"

  github.com/nkolesnikov999/micro2-OK/order/internal/service:
    config:
      include-regex: ".*Service"

  github.com/nkolesnikov999/micro2-OK/order/internal/repository:
    config:
      include-regex: ".*Repository"

  github.com/nkolesnikov999/micro2-OK/order/internal/config:
    config:
      include-regex: ".*Config"

  github.com/nkolesnikov999/micro2-OK/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/nkolesnikov999/micro2-OK/payment/internal/config:
    config:
      include-regex: ".*Config"

  github.com/nkolesnikov999/micro2-OK/order/internal/client/grpc:
    config:
      include-regex: ".*Client"

  github.com/nkolesnikov999/micro2-OK/assembly/internal/service:
    config:
      include-regex: ".*Service"

  github.com/nkolesnikov999/micro2-OK/assembly/internal/config:
    config:
      include-regex: ".*Config"
