// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/assembly/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// ShipAssembledProducerService is an autogenerated mock type for the ShipAssembledProducerService type
type ShipAssembledProducerService struct {
	mock.Mock
}

type ShipAssembledProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *ShipAssembledProducerService) EXPECT() *ShipAssembledProducerService_Expecter {
	return &ShipAssembledProducerService_Expecter{mock: &_m.Mock}
}

// ProduceShipAssembled provides a mock function with given fields: ctx, event
func (_m *ShipAssembledProducerService) ProduceShipAssembled(ctx context.Context, event model.ShipAssembledEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceShipAssembled")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ShipAssembledEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShipAssembledProducerService_ProduceShipAssembled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceShipAssembled'
type ShipAssembledProducerService_ProduceShipAssembled_Call struct {
	*mock.Call
}

// ProduceShipAssembled is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.ShipAssembledEvent
func (_e *ShipAssembledProducerService_Expecter) ProduceShipAssembled(ctx interface{}, event interface{}) *ShipAssembledProducerService_ProduceShipAssembled_Call {
	return &ShipAssembledProducerService_ProduceShipAssembled_Call{Call: _e.mock.On("ProduceShipAssembled", ctx, event)}
}

func (_c *ShipAssembledProducerService_ProduceShipAssembled_Call) Run(run func(ctx context.Context, event model.ShipAssembledEvent)) *ShipAssembledProducerService_ProduceShipAssembled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ShipAssembledEvent))
	})
	return _c
}

func (_c *ShipAssembledProducerService_ProduceShipAssembled_Call) Return(_a0 error) *ShipAssembledProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShipAssembledProducerService_ProduceShipAssembled_Call) RunAndReturn(run func(context.Context, model.ShipAssembledEvent) error) *ShipAssembledProducerService_ProduceShipAssembled_Call {
	_c.Call.Return(run)
	return _c
}

// NewShipAssembledProducerService creates a new instance of ShipAssembledProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShipAssembledProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShipAssembledProducerService {
	mock := &ShipAssembledProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
