// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/v1/order.proto

package events_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Заказ зарегистрирован
type OrderPaidRecorded struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EventUuid       string                 `protobuf:"bytes,1,opt,name=event_uuid,json=eventUuid,proto3" json:"event_uuid,omitempty"`                   // Уникальный идентификатор события (для идемпотентности)
	OrderUuid       string                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`                   // Идентификатор оплаченного заказа
	UserUuid        string                 `protobuf:"bytes,3,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`                      // Идентификатор пользователя
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`       // Способ оплаты (строкой, значение из PaymentMethod)
	TransactionUuid string                 `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"` // Идентификатор транзакции, сгенерированный в результате оплаты
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderPaidRecorded) Reset() {
	*x = OrderPaidRecorded{}
	mi := &file_events_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderPaidRecorded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderPaidRecorded) ProtoMessage() {}

func (x *OrderPaidRecorded) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderPaidRecorded.ProtoReflect.Descriptor instead.
func (*OrderPaidRecorded) Descriptor() ([]byte, []int) {
	return file_events_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderPaidRecorded) GetEventUuid() string {
	if x != nil {
		return x.EventUuid
	}
	return ""
}

func (x *OrderPaidRecorded) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *OrderPaidRecorded) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *OrderPaidRecorded) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *OrderPaidRecorded) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

var File_events_v1_order_proto protoreflect.FileDescriptor

const file_events_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x15events/v1/order.proto\x12\tevents.v1\"\xc0\x01\n" +
	"\x11OrderPaidRecorded\x12\x1d\n" +
	"\n" +
	"event_uuid\x18\x01 \x01(\tR\teventUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x03 \x01(\tR\buserUuid\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12)\n" +
	"\x10transaction_uuid\x18\x05 \x01(\tR\x0ftransactionUuidBJZHgithub.com/nkolesnikov999/micro2-OK/shared/pkg/proto/events/v1;events_v1b\x06proto3"

var (
	file_events_v1_order_proto_rawDescOnce sync.Once
	file_events_v1_order_proto_rawDescData []byte
)

func file_events_v1_order_proto_rawDescGZIP() []byte {
	file_events_v1_order_proto_rawDescOnce.Do(func() {
		file_events_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)))
	})
	return file_events_v1_order_proto_rawDescData
}

var file_events_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_events_v1_order_proto_goTypes = []any{
	(*OrderPaidRecorded)(nil), // 0: events.v1.OrderPaidRecorded
}
var file_events_v1_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_events_v1_order_proto_init() }
func file_events_v1_order_proto_init() {
	if File_events_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_order_proto_rawDesc), len(file_events_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_order_proto_goTypes,
		DependencyIndexes: file_events_v1_order_proto_depIdxs,
		MessageInfos:      file_events_v1_order_proto_msgTypes,
	}.Build()
	File_events_v1_order_proto = out.File
	file_events_v1_order_proto_goTypes = nil
	file_events_v1_order_proto_depIdxs = nil
}
