// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/iam/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepository is an autogenerated mock type for the SessionRepository type
type SessionRepository struct {
	mock.Mock
}

type SessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepository) EXPECT() *SessionRepository_Expecter {
	return &SessionRepository_Expecter{mock: &_m.Mock}
}

// AddSessionToUserSet provides a mock function with given fields: ctx, userUUID, sessionUUID
func (_m *SessionRepository) AddSessionToUserSet(ctx context.Context, userUUID string, sessionUUID string) error {
	ret := _m.Called(ctx, userUUID, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for AddSessionToUserSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userUUID, sessionUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_AddSessionToUserSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSessionToUserSet'
type SessionRepository_AddSessionToUserSet_Call struct {
	*mock.Call
}

// AddSessionToUserSet is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
//   - sessionUUID string
func (_e *SessionRepository_Expecter) AddSessionToUserSet(ctx interface{}, userUUID interface{}, sessionUUID interface{}) *SessionRepository_AddSessionToUserSet_Call {
	return &SessionRepository_AddSessionToUserSet_Call{Call: _e.mock.On("AddSessionToUserSet", ctx, userUUID, sessionUUID)}
}

func (_c *SessionRepository_AddSessionToUserSet_Call) Run(run func(ctx context.Context, userUUID string, sessionUUID string)) *SessionRepository_AddSessionToUserSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *SessionRepository_AddSessionToUserSet_Call) Return(_a0 error) *SessionRepository_AddSessionToUserSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_AddSessionToUserSet_Call) RunAndReturn(run func(context.Context, string, string) error) *SessionRepository_AddSessionToUserSet_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, session, ttl
func (_m *SessionRepository) CreateSession(ctx context.Context, session model.Session, ttl time.Duration) error {
	ret := _m.Called(ctx, session, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Session, time.Duration) error); ok {
		r0 = rf(ctx, session, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type SessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session model.Session
//   - ttl time.Duration
func (_e *SessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}, ttl interface{}) *SessionRepository_CreateSession_Call {
	return &SessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session, ttl)}
}

func (_c *SessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session model.Session, ttl time.Duration)) *SessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Session), args[2].(time.Duration))
	})
	return _c
}

func (_c *SessionRepository_CreateSession_Call) Return(_a0 error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SessionRepository_CreateSession_Call) RunAndReturn(run func(context.Context, model.Session, time.Duration) error) *SessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: ctx, sessionUUID
func (_m *SessionRepository) GetSession(ctx context.Context, sessionUUID string) (model.Session, error) {
	ret := _m.Called(ctx, sessionUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 model.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Session, error)); ok {
		return rf(ctx, sessionUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Session); ok {
		r0 = rf(ctx, sessionUUID)
	} else {
		r0 = ret.Get(0).(model.Session)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SessionRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type SessionRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionUUID string
func (_e *SessionRepository_Expecter) GetSession(ctx interface{}, sessionUUID interface{}) *SessionRepository_GetSession_Call {
	return &SessionRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, sessionUUID)}
}

func (_c *SessionRepository_GetSession_Call) Run(run func(ctx context.Context, sessionUUID string)) *SessionRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *SessionRepository_GetSession_Call) Return(_a0 model.Session, _a1 error) *SessionRepository_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SessionRepository_GetSession_Call) RunAndReturn(run func(context.Context, string) (model.Session, error)) *SessionRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewSessionRepository creates a new instance of SessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepository {
	mock := &SessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
