// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/iam/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, user, passwordHash
func (_m *UserRepository) CreateUser(ctx context.Context, user model.User, passwordHash string) error {
	ret := _m.Called(ctx, user, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User, string) error); ok {
		r0 = rf(ctx, user, passwordHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.User
//   - passwordHash string
func (_e *UserRepository_Expecter) CreateUser(ctx interface{}, user interface{}, passwordHash interface{}) *UserRepository_CreateUser_Call {
	return &UserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user, passwordHash)}
}

func (_c *UserRepository_CreateUser_Call) Run(run func(ctx context.Context, user model.User, passwordHash string)) *UserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_CreateUser_Call) Return(_a0 error) *UserRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, model.User, string) error) *UserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userUUID
func (_m *UserRepository) GetUser(ctx context.Context, userUUID string) (model.User, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, userUUID)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID string
func (_e *UserRepository_Expecter) GetUser(ctx interface{}, userUUID interface{}) *UserRepository_GetUser_Call {
	return &UserRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userUUID)}
}

func (_c *UserRepository_GetUser_Call) Run(run func(ctx context.Context, userUUID string)) *UserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetUser_Call) Return(_a0 model.User, _a1 error) *UserRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetUser_Call) RunAndReturn(run func(context.Context, string) (model.User, error)) *UserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLoginOrEmail provides a mock function with given fields: ctx, loginOrEmail
func (_m *UserRepository) GetUserByLoginOrEmail(ctx context.Context, loginOrEmail string) (model.User, string, error) {
	ret := _m.Called(ctx, loginOrEmail)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLoginOrEmail")
	}

	var r0 model.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.User, string, error)); ok {
		return rf(ctx, loginOrEmail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = rf(ctx, loginOrEmail)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, loginOrEmail)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, loginOrEmail)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UserRepository_GetUserByLoginOrEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLoginOrEmail'
type UserRepository_GetUserByLoginOrEmail_Call struct {
	*mock.Call
}

// GetUserByLoginOrEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - loginOrEmail string
func (_e *UserRepository_Expecter) GetUserByLoginOrEmail(ctx interface{}, loginOrEmail interface{}) *UserRepository_GetUserByLoginOrEmail_Call {
	return &UserRepository_GetUserByLoginOrEmail_Call{Call: _e.mock.On("GetUserByLoginOrEmail", ctx, loginOrEmail)}
}

func (_c *UserRepository_GetUserByLoginOrEmail_Call) Run(run func(ctx context.Context, loginOrEmail string)) *UserRepository_GetUserByLoginOrEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetUserByLoginOrEmail_Call) Return(_a0 model.User, _a1 string, _a2 error) *UserRepository_GetUserByLoginOrEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UserRepository_GetUserByLoginOrEmail_Call) RunAndReturn(run func(context.Context, string) (model.User, string, error)) *UserRepository_GetUserByLoginOrEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
