// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// HTTPConfig is an autogenerated mock type for the HTTPConfig type
type HTTPConfig struct {
	mock.Mock
}

type HTTPConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPConfig) EXPECT() *HTTPConfig_Expecter {
	return &HTTPConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *HTTPConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HTTPConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type HTTPConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *HTTPConfig_Expecter) Address() *HTTPConfig_Address_Call {
	return &HTTPConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *HTTPConfig_Address_Call) Run(run func()) *HTTPConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HTTPConfig_Address_Call) Return(_a0 string) *HTTPConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HTTPConfig_Address_Call) RunAndReturn(run func() string) *HTTPConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTimeout provides a mock function with no fields
func (_m *HTTPConfig) ReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// HTTPConfig_ReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTimeout'
type HTTPConfig_ReadTimeout_Call struct {
	*mock.Call
}

// ReadTimeout is a helper method to define mock.On call
func (_e *HTTPConfig_Expecter) ReadTimeout() *HTTPConfig_ReadTimeout_Call {
	return &HTTPConfig_ReadTimeout_Call{Call: _e.mock.On("ReadTimeout")}
}

func (_c *HTTPConfig_ReadTimeout_Call) Run(run func()) *HTTPConfig_ReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HTTPConfig_ReadTimeout_Call) Return(_a0 time.Duration) *HTTPConfig_ReadTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HTTPConfig_ReadTimeout_Call) RunAndReturn(run func() time.Duration) *HTTPConfig_ReadTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// ShutdownTimeout provides a mock function with no fields
func (_m *HTTPConfig) ShutdownTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShutdownTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// HTTPConfig_ShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShutdownTimeout'
type HTTPConfig_ShutdownTimeout_Call struct {
	*mock.Call
}

// ShutdownTimeout is a helper method to define mock.On call
func (_e *HTTPConfig_Expecter) ShutdownTimeout() *HTTPConfig_ShutdownTimeout_Call {
	return &HTTPConfig_ShutdownTimeout_Call{Call: _e.mock.On("ShutdownTimeout")}
}

func (_c *HTTPConfig_ShutdownTimeout_Call) Run(run func()) *HTTPConfig_ShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HTTPConfig_ShutdownTimeout_Call) Return(_a0 time.Duration) *HTTPConfig_ShutdownTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HTTPConfig_ShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *HTTPConfig_ShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewHTTPConfig creates a new instance of HTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPConfig {
	mock := &HTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
