// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MetricCollectorConfig is an autogenerated mock type for the MetricCollectorConfig type
type MetricCollectorConfig struct {
	mock.Mock
}

type MetricCollectorConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricCollectorConfig) EXPECT() *MetricCollectorConfig_Expecter {
	return &MetricCollectorConfig_Expecter{mock: &_m.Mock}
}

// CollectorEndpoint provides a mock function with no fields
func (_m *MetricCollectorConfig) CollectorEndpoint() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectorEndpoint")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MetricCollectorConfig_CollectorEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectorEndpoint'
type MetricCollectorConfig_CollectorEndpoint_Call struct {
	*mock.Call
}

// CollectorEndpoint is a helper method to define mock.On call
func (_e *MetricCollectorConfig_Expecter) CollectorEndpoint() *MetricCollectorConfig_CollectorEndpoint_Call {
	return &MetricCollectorConfig_CollectorEndpoint_Call{Call: _e.mock.On("CollectorEndpoint")}
}

func (_c *MetricCollectorConfig_CollectorEndpoint_Call) Run(run func()) *MetricCollectorConfig_CollectorEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricCollectorConfig_CollectorEndpoint_Call) Return(_a0 string) *MetricCollectorConfig_CollectorEndpoint_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricCollectorConfig_CollectorEndpoint_Call) RunAndReturn(run func() string) *MetricCollectorConfig_CollectorEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// CollectorInterval provides a mock function with no fields
func (_m *MetricCollectorConfig) CollectorInterval() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectorInterval")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MetricCollectorConfig_CollectorInterval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectorInterval'
type MetricCollectorConfig_CollectorInterval_Call struct {
	*mock.Call
}

// CollectorInterval is a helper method to define mock.On call
func (_e *MetricCollectorConfig_Expecter) CollectorInterval() *MetricCollectorConfig_CollectorInterval_Call {
	return &MetricCollectorConfig_CollectorInterval_Call{Call: _e.mock.On("CollectorInterval")}
}

func (_c *MetricCollectorConfig_CollectorInterval_Call) Run(run func()) *MetricCollectorConfig_CollectorInterval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricCollectorConfig_CollectorInterval_Call) Return(_a0 time.Duration) *MetricCollectorConfig_CollectorInterval_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricCollectorConfig_CollectorInterval_Call) RunAndReturn(run func() time.Duration) *MetricCollectorConfig_CollectorInterval_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceName provides a mock function with no fields
func (_m *MetricCollectorConfig) ServiceName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MetricCollectorConfig_ServiceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceName'
type MetricCollectorConfig_ServiceName_Call struct {
	*mock.Call
}

// ServiceName is a helper method to define mock.On call
func (_e *MetricCollectorConfig_Expecter) ServiceName() *MetricCollectorConfig_ServiceName_Call {
	return &MetricCollectorConfig_ServiceName_Call{Call: _e.mock.On("ServiceName")}
}

func (_c *MetricCollectorConfig_ServiceName_Call) Run(run func()) *MetricCollectorConfig_ServiceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MetricCollectorConfig_ServiceName_Call) Return(_a0 string) *MetricCollectorConfig_ServiceName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricCollectorConfig_ServiceName_Call) RunAndReturn(run func() string) *MetricCollectorConfig_ServiceName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetricCollectorConfig creates a new instance of MetricCollectorConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricCollectorConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricCollectorConfig {
	mock := &MetricCollectorConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
