// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderPaidProducerService is an autogenerated mock type for the OrderPaidProducerService type
type OrderPaidProducerService struct {
	mock.Mock
}

type OrderPaidProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPaidProducerService) EXPECT() *OrderPaidProducerService_Expecter {
	return &OrderPaidProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaid provides a mock function with given fields: ctx, event
func (_m *OrderPaidProducerService) ProduceOrderPaid(ctx context.Context, event model.OrderPaidEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderPaidProducerService_ProduceOrderPaid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaid'
type OrderPaidProducerService_ProduceOrderPaid_Call struct {
	*mock.Call
}

// ProduceOrderPaid is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidEvent
func (_e *OrderPaidProducerService_Expecter) ProduceOrderPaid(ctx interface{}, event interface{}) *OrderPaidProducerService_ProduceOrderPaid_Call {
	return &OrderPaidProducerService_ProduceOrderPaid_Call{Call: _e.mock.On("ProduceOrderPaid", ctx, event)}
}

func (_c *OrderPaidProducerService_ProduceOrderPaid_Call) Run(run func(ctx context.Context, event model.OrderPaidEvent)) *OrderPaidProducerService_ProduceOrderPaid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidEvent))
	})
	return _c
}

func (_c *OrderPaidProducerService_ProduceOrderPaid_Call) Return(_a0 error) *OrderPaidProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderPaidProducerService_ProduceOrderPaid_Call) RunAndReturn(run func(context.Context, model.OrderPaidEvent) error) *OrderPaidProducerService_ProduceOrderPaid_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPaidProducerService creates a new instance of OrderPaidProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPaidProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPaidProducerService {
	mock := &OrderPaidProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
