// Code generated for micro2-OK service
// © nk 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nkolesnikov999/micro2-OK/order/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// OrderProducerService is an autogenerated mock type for the OrderProducerService type
type OrderProducerService struct {
	mock.Mock
}

type OrderProducerService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderProducerService) EXPECT() *OrderProducerService_Expecter {
	return &OrderProducerService_Expecter{mock: &_m.Mock}
}

// ProduceOrderPaidRecorded provides a mock function with given fields: ctx, event
func (_m *OrderProducerService) ProduceOrderPaidRecorded(ctx context.Context, event model.OrderPaidRecordedEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProduceOrderPaidRecorded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OrderPaidRecordedEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderProducerService_ProduceOrderPaidRecorded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceOrderPaidRecorded'
type OrderProducerService_ProduceOrderPaidRecorded_Call struct {
	*mock.Call
}

// ProduceOrderPaidRecorded is a helper method to define mock.On call
//   - ctx context.Context
//   - event model.OrderPaidRecordedEvent
func (_e *OrderProducerService_Expecter) ProduceOrderPaidRecorded(ctx interface{}, event interface{}) *OrderProducerService_ProduceOrderPaidRecorded_Call {
	return &OrderProducerService_ProduceOrderPaidRecorded_Call{Call: _e.mock.On("ProduceOrderPaidRecorded", ctx, event)}
}

func (_c *OrderProducerService_ProduceOrderPaidRecorded_Call) Run(run func(ctx context.Context, event model.OrderPaidRecordedEvent)) *OrderProducerService_ProduceOrderPaidRecorded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OrderPaidRecordedEvent))
	})
	return _c
}

func (_c *OrderProducerService_ProduceOrderPaidRecorded_Call) Return(_a0 error) *OrderProducerService_ProduceOrderPaidRecorded_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderProducerService_ProduceOrderPaidRecorded_Call) RunAndReturn(run func(context.Context, model.OrderPaidRecordedEvent) error) *OrderProducerService_ProduceOrderPaidRecorded_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderProducerService creates a new instance of OrderProducerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProducerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProducerService {
	mock := &OrderProducerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
